version: '3'

services:
  app:
    build: . # Gunakan Dockerfile yang berada di direktori app/
    ports:
      - "8001:8001" # Port host : Port container
    env_file:
      -  .env.develop # Contoh pengaturan variabel lingkungan
    volumes:
      - ./app:/app # Volume mapping untuk memperbarui perubahan langsung