version: '3'

services:
  app:
    build: . # Gunakan Dockerfile yang berada di direktori app/
    ports:
      - "3000:3000" # Port host : Port container
    env_file:
      -  .env.production # Contoh pengaturan variabel lingkungan
    # volumes:
    #   - ./app:/app # Volume mapping untuk memperbarui perubahan langsung